### ISSUE TITLE
Great job, but where are the scripts?

### ISSUE THREAD

**Issue by cybershrapnel** [jetdog8808/JetDogs-Prefabs#1]
Messed around with this a bit tonight, was going ot use it as a landing zone for my world I was building... Seems to be missing some scripts though and such... Is not loading into unity fully from a new project... Tested several times unless I am missing something stupid...

I did get it to work by changing a few things without your scripts but the room doesn't do the cool lighting effect and I can't seem to get full textures on the doors if I copy one...??? a bit confused....

But great work!!!! Me and you may need to talk :) big plans

**Comment by jetdog8808** [comment]
the only scripts it should be using are components from the vrchat sdk, one from the standard assets, and post processing stack for cameras. it sounds like your having problems with the theater. the reference camera has a post processing stack applied. it can be removed and the problem will be fixed. or you can download it from the unity asset store and youll be able to use it.

**Comment by cybershrapnel** [comment]
cool, I'll check it out from the store then...

**Comment by cybershrapnel** [comment]
btw, Can't seem to find your asset on the store.  And yes the theater is what I am talking about of course :)

The "video panel" scene loads and works just fine, but has no ambient lighting as we were discussing.

The "Stream Panel" scene which I assume is the working good one from the current public world is not working. Shows 2 missing scripts and the texture is missing for the screen.

I tried replacing the texture and it will not play, where as the video in the other scene will play...

![image](https://user-images.githubusercontent.com/17352697/42234230-bb2cef30-7ea8-11e8-9591-1311c17464a8.png)

**Comment by cybershrapnel** [comment]
I redownloaded your package and made a new project and reimported the sdk since it looks liek you updated it 4 hours ago...

now it shows this..
![image](https://user-images.githubusercontent.com/17352697/42235096-83ef5726-7eab-11e8-9ef7-49af20556929.png)

Still missing one script... Which script is not showing there??? can u tell me...

**Comment by cybershrapnel** [comment]
I feel like I am missing a base SDK script, Was the SDK updated or something...

**Comment by jetdog8808** [comment]
![image](https://user-images.githubusercontent.com/36026251/42236208-da5caf32-7ebf-11e8-9e02-e783f5ae7d03.png)
ya it looks like your sdk might not be up to date.
vrchat sdk should be. 
![image](https://user-images.githubusercontent.com/36026251/42236275-108882a2-7ec0-11e8-92fd-662fa766b018.png)

**Comment by cybershrapnel** [comment]
YUP!!! LOL!!! AWESOME!

and frustrating... It's working fine now, /sigh. I was runing on the 6/10 SDk now I am on 6/21

Glad to see someone that responds too :) We'll be chattin
